platform :ios, '8.0'
use_frameworks!

pod 'AFNetworking'
pod 'FDFullscreenPopGesture'
pod 'MJExtension'
pod 'SUIMVVMNetwork' 
pod 'MJRefresh'
pod 'SwiftExtensionKit'
pod 'UITableView+FDTemplateLayoutCell'
source 'https://github.com/CocoaPods/Specs.git'
pod 'SnapKit'
